# generated by datamodel-codegen:
#   filename:  sample_receipes.json
#   timestamp: 2024-11-11T14:46:13+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, RootModel


class Ingredient(BaseModel):
    item: Optional[str] = None
    quantity: Optional[Union[float, str]] = None
    unit: Optional[str] = None


class Recipe(BaseModel):
    title: Optional[str] = None
    page: Optional[int] = None
    author: Optional[str] = None
    ingredients: Optional[List[Ingredient]] = None
    instructions: Optional[List[str]] = None


class CookBook(BaseModel):
    recipes: List[Recipe]
